### ISSUE TITLE
Update email address on profile

### ISSUE THREAD

**Issue by damalgos** [GladysProject/gladys-gateway#1]
The email address should be able to be changed without changing the password at the same time.

**Comment by Pierre-Gilles** [comment]
Hi!

I should explain why, but there is a reason why it's not possible :p 

The Gladys Gateway is not a traditional backend:

-> your password is never sent to the backend
-> your private keys are encrypted with a hash composed of the email + password

If you want to change the email or password, the keys need to be encrypted again so the password should be provided (even if it's the same password)

But you're right it's not clear enough right now why :)
